---
title: "Lymphatic Graphs"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---


```{r}
library(tidyverse)
library(car)
summ4.df = readRDS("TEST.rds")
summ5.df = readRDS("TEST_sum.rds")

make_graph = function(all_data, summ_data, ylab, variable_name)
{

all_data$variable = all_data[[variable_name]]
summ_data$variable = summ_data[[variable_name]]
summ_data$std = summ_data[[paste(variable_name, "_std", sep = "")]]

print(summ_data %>% dplyr::select(`treatment`, `n`))


plot(ggplot(all_data) + geom_boxplot(aes(y = variable, x = treatment)) +
  geom_point(aes(y = variable, x = treatment), color = "blue", shape = 16, size = 3, alpha = 0.3) +
  scale_y_continuous(limits = c(NA,NA)) +
  labs(y = ylab, x = ""))

plot(ggplot(summ_data) + geom_col(aes(y = variable, x = treatment)) +
  geom_errorbar(aes(y = variable, x = treatment, ymax = (variable + std), ymin = (variable-std))) +
  labs(y = ylab, x = ""))

plot(ggplot(summ_data) + geom_col(aes(y = variable, x = treatment)) +
  geom_errorbar(aes(y = variable, x = treatment, ymax = (variable + std), ymin = (variable-std))) +
  labs(y = ylab, x = "")+
  geom_point(aes(y = variable, x = treatment), data = all_data, color = "blue", shape = 16, size = 3, alpha = 0.3))

# Compute the analysis of variance
res.aov <- aov(variable ~ treatment, data = all_data)
print(summary(res.aov))
print(TukeyHSD(res.aov))


print(leveneTest(variable ~ treatment, data = all_data))
aov_residuals <- residuals(object = res.aov)
print(shapiro.test(x = aov_residuals))
print(kruskal.test(variable ~ treatment, data = all_data))

print(pairwise.wilcox.test(all_data$variable, all_data$treatment,
                     p.adjust.method = "fdr"))
}


```

\newpage
# Mean Contraction Frequency

```{r}

make_graph(summ4.df, summ5.df, "Mean contractions / vessel / min", "max_n_cont")

```
\newpage
# Average contraction amplitude

```{r}

make_graph(summ4.df, summ5.df, "Mean pixels / vessel", "mean_mag")

```
\newpage
# Average Diameter

```{r}

make_graph(all_data = summ4.df, summ_data = summ5.df, ylab = "Mean pixels / vessel", variable_name = "width")


```


\newpage
# Mean Fractional Pump Flow


```{r}

make_graph(all_data = summ4.df, summ_data = summ5.df, ylab = "Mean pixels / vessel / min", variable_name = "fpf")


```
\newpage
# Mean ejection fraction

```{r}

make_graph(all_data = summ4.df, summ_data = summ5.df, ylab = "Mean Ejection Fraction", variable_name = "ef")

```
\newpage
# Average overall contraction duration

```{r}

make_graph(all_data = summ4.df, summ_data = summ5.df, ylab = "Average Overall Contraction Duration / Vessel", variable_name = "duration")

```


\newpage
# Average contraction phase duration
```{r}
make_graph(all_data = summ4.df, summ_data = summ5.df, ylab = "Mean Contraction phase duration", variable_name = "cont_duration")
```

\newpage
# Average fill phase duration

```{r}
make_graph(all_data = summ4.df, summ_data = summ5.df, ylab = "Mean Fill phase duration", variable_name = "fill_duration")
```










