---
title: "Lymphatic Graphs"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---


```{r}
library(tidyverse)
summ4.df = readRDS("TEST.rds")
```



```{r}

ggplot(summ4.df) + geom_boxplot(aes(y = max_n_cont*2, x = treatment)) +
  geom_point(aes(y = max_n_cont*2, x = treatment), color = "blue", shape = 1, size = 3) +
  scale_y_continuous(limits = c(NA,NA)) +
  labs(y = "Average Contraction Frequency / Vessel", x = "")

# Compute the analysis of variance
res.aov <- aov(max_n_cont ~ treatment, data = summ4.df)
summary(res.aov)
TukeyHSD(res.aov)

```


```{r}

ggplot(summ4.df) + geom_boxplot(aes(y = mean_mag, x = treatment)) +
  geom_point(aes(y = mean_mag, x = treatment), color = "blue", position = "dodge") +
  scale_y_continuous(limits = c(NA,NA)) +
  labs(y = "Average Contraction Amplitude / Vessel", x = "")

# Compute the analysis of variance
res.aov <- aov(mean_mag ~ treatment, data = summ4.df)
summary(res.aov)
TukeyHSD(res.aov)

```


```{r}

ggplot(summ4.df) + geom_boxplot(aes(y = width, x = treatment)) +
  geom_point(aes(y = width, x = treatment), color = "blue", position = "dodge") +
  scale_y_continuous(limits = c(NA,NA)) +
  labs(y = "Average Diameter / Vessel", x = "")

# Compute the analysis of variance
res.aov <- aov(width ~ treatment, data = summ4.df)
summary(res.aov)
TukeyHSD(res.aov)

```


```{r}
ggplot(summ4.df) + geom_boxplot(aes(y = duration, x = treatment)) +
  geom_point(aes(y = duration, x = treatment), color = "blue", position = "dodge") +
  scale_y_continuous(limits = c(NA,NA)) +
  labs(y = "Average Contraction Duration / Vessel", x = "")

# Compute the analysis of variance
res.aov <- aov(duration ~ treatment, data = summ4.df)
summary(res.aov)
TukeyHSD(res.aov)
```






```{r}


ggplot(summ4.df) + geom_boxplot(aes(y = fpf, x = treatment)) +
  geom_point(aes(y = fpf, x = treatment), color = "blue", position = "dodge") +
  scale_y_continuous(limits = c(0,NA)) +
  labs(y = "Mean Fractional Pump Flow", x = "")

# Compute the analysis of variance
res.aov <- aov(fpf ~ treatment, data = summ4.df)
summary(res.aov)
TukeyHSD(res.aov)



```


```{r}
ggplot(summ4.df) + geom_boxplot(aes(y = ef, x = treatment)) +
  geom_point(aes(y = ef, x = treatment), color = "blue", position = "dodge") +
  scale_y_continuous(limits = c(0,NA)) +
  labs(y = "Mean Ejection Fraction", x = "")

# Compute the analysis of variance
res.aov <- aov(ef ~ treatment, data = summ4.df)
summary(res.aov)
TukeyHSD(res.aov)
```




