---
title: "Lymphatic Graphs"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---


```{r}
library(tidyverse)
library(car)
summ4.df = readRDS("TEST.rds")
summ5.df = readRDS("TEST_sum.rds")

make_graph = function(all_data, summ_data, ylab, variable_name)
{

all_data$variable = all_data[[variable_name]]
summ_data$variable = summ_data[[variable_name]]
summ_data$std = summ_data[[paste(variable_name, "_std", sep = "")]]


plot(ggplot(all_data) + geom_boxplot(aes(y = variable, x = treatment)) +
  geom_point(aes(y = variable, x = treatment), color = "blue", shape = 1, size = 3) +
  scale_y_continuous(limits = c(NA,NA)) +
  labs(y = ylab, x = ""))

plot(ggplot(summ_data) + geom_col(aes(y = variable, x = treatment)) +
  geom_errorbar(aes(y = variable, x = treatment, ymax = (variable + std), ymin = (variable-std))) +
  labs(y = ylab, x = ""))

plot(ggplot(summ_data) + geom_col(aes(y = variable, x = treatment)) +
  geom_errorbar(aes(y = variable, x = treatment, ymax = (variable + std), ymin = (variable-std))) +
  labs(y = ylab, x = "")+
  geom_point(aes(y = variable, x = treatment), data = all_data, color = "blue", shape = 1, size = 3))

# Compute the analysis of variance
res.aov <- aov(variable ~ treatment, data = all_data)
print(summary(res.aov))
print(TukeyHSD(res.aov))


print(leveneTest(variable ~ treatment, data = all_data))
aov_residuals <- residuals(object = res.aov)
print(shapiro.test(x = aov_residuals))
kruskal.test(variable ~ treatment, data = all_data)

pairwise.wilcox.test(all_data$variable, all_data$treatment,
                     p.adjust.method = "fdr")
}


```



```{r}

make_graph(summ4.df, summ5.df, "Mean Contraction Frequency / Vessel / Minute", "max_n_cont")

```


```{r}

make_graph(summ4.df, summ5.df, "Average Contraction Amplitude / Vessel", "mean_mag")

```


```{r}

make_graph(all_data = summ4.df, summ_data = summ5.df, ylab = "Average Diameter / Vessel", variable_name = "width")


```


```{r}

make_graph(all_data = summ4.df, summ_data = summ5.df, ylab = "Average Contraction Duration / Vessel", variable_name = "duration")

```






```{r}

make_graph(all_data = summ4.df, summ_data = summ5.df, ylab = "Mean Fractional Pump Flow", variable_name = "fpf")


ggplot(summ4.df) + geom_boxplot(aes(y = fpf, x = treatment)) +
  geom_point(aes(y = fpf, x = treatment), color = "blue", shape = 1, size = 3) +
  scale_y_continuous(limits = c(0,NA)) +
  labs(y = "Mean Fractional Pump Flow", x = "")

# Compute the analysis of variance
res.aov <- aov(fpf ~ treatment, data = summ4.df)
summary(res.aov)
TukeyHSD(res.aov)



```


```{r}
ggplot(summ4.df) + geom_boxplot(aes(y = ef, x = treatment)) +
  geom_point(aes(y = ef, x = treatment), color = "blue", shape = 1, size = 3) +
  scale_y_continuous(limits = c(0,NA)) +
  labs(y = "Mean Ejection Fraction", x = "")

# Compute the analysis of variance
res.aov <- aov(ef ~ treatment, data = summ4.df)
summary(res.aov)
TukeyHSD(res.aov)
```




